Add fixes

diff --git a/scripts/contribute b/scripts/contribute
--- a/scripts/contribute
+++ b/scripts/contribute
@@ -1,59 +1,17 @@
 #!/bin/bash
+# set -u
+set -x
 
-GITHUB_REPO="vocdoni/zk-voceremony"
+GITHUB_REPO="Kolezhniuk/zk-voceremony"
 
 intro_message() {
-    echo "
 
-       __     __   ______    ______   _______    ______   __    __  ______                                                                        
-      |  \   |  \ /      \  /      \ |       \  /      \ |  \  |  \|      \ 
-      | ##   | ##|  ######\|  ######\| #######\|  ######\| ##\ | ## \######
-      | ##   | ##| ##  | ##| ##   \##| ##  | ##| ##  | ##| ###\| ##  | ##     
-       \##\ /  ##| ##  | ##| ##      | ##  | ##| ##  | ##| ####\ ##  | ##
-        \##\  ## | ##  | ##| ##   __ | ##  | ##| ##  | ##| ##\## ##  | ##    
-         \## ##  | ##__/ ##| ##__/  \| ##__/ ##| ##__/ ##| ## \#### _| ##_
-          \###    \##    ## \##    ##| ##    ## \##    ##| ##  \###|   ## \  
-           \#      \######   \######  \#######   \######  \##   \## \######    
-
-                 zk-SNARKs Anonymous Voting Trusted Setup Ceremony 
-                                                                        
-                                   ,******,*,.                                 
-                                   *********,,,,,,,,.                             
-                                  *//*********,,,,,,                              
-                                  //////**********,.                               
-                             .,**///////////*******.                                
-                       .*********(((////////////***,,,,,,.                          
-                .**************,*((((((((/////////*,,,,,,,,,,,,.                          
-          ,********/////////////////((((((((//////,,,,,,,,,,,,.........              
-       (/***************///////////*******//(((((/*,,,,,,,,,,,...........,            
-       (#(((((/*,***********/..***/************,,,*,,,,,,,,,.......,,,,,,,                
-       ((##((((((((/*,,*********,,,,,,,,,,,,,,,,,,,,,,,,,...,******,***,,,          
-       #(((((((((((((((((/*,,,,,,,,,,,,,,,,,,,,,,,,...,***********,,,,,,,,           
-       #(((((((((((//((((((((///*,.,,,,,,,,,,...,***///**//*,,****,,,,,,,,     
-       ##((((((((((((((((//(((((//////*,..,**/////////************,,,,,,,,      
-       ##(((((((((((((((((((((///(((////*///////***/***************,,,,,,,      
-       ####(((((((((((((((((((//////////*/**//////////****************,,,,      
-       ######(((((((((((((((((/(////////*///////////////*****************,      
-       (#######(((((((((((((((((////////*///////////////////*************,      
-       (#########((((((((((((((((///////*//////////////////////**********,      
-       /##########(((((((((((((((((/////*////////////////////////********.      
-       /############(((((((((((((((((((/*/////////////////////////*******.      
-        /%############((((((((((((((((((*//////////////////////////////.        
-             *###########(((((((((((((((//(///((((((((//////////(/.             
-                  .########(((((((((((((/((((((((((((((((((((.                  
-                       ./#####((((((((((/(((((((((((((((.                       
-                             *####((((((/((((((((((.                            
-                                  .###((/(((((.                                 
-                                        *.
-"
-    echo
-    echo "Welcome to the zk-voceremony contribution process!"
+    echo "Welcome to the zk-ceremony contribution process!"
     echo
     echo "To start your contribution you need to provide the following information:"
     echo " - The github repository of the ceremony (by default '$GITHUB_REPO')"
     echo " - Login to your GitHub account (commits will use your github username)"
 }
-
 
 prompt_env_inputs() {
     read -p "Enter the name of the repo (by default '$GITHUB_REPO'): " REPO_URL
@@ -62,8 +20,8 @@ prompt_env_inputs() {
     fi
 
     # list on-going ceremonies
-    branches="$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" \
-                | jq '.[].head.ref' | tr -d '"' | grep ^ceremony | sort -u )"
+    branches="$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" |
+        jq '.[].head.ref' | tr -d '"' | grep ^ceremony | sort -u)"
     echo
     echo "Current on-going ceremonies:"
     echo
@@ -76,10 +34,10 @@ prompt_env_inputs() {
     fi
 
     echo
-    while curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" \
-    | jq '.[].title' | grep Contribution | grep $CEREMONY_BRANCH ; do
-      echo "Oops, there's a PR from someone *right now* uploading a contribution to this ceremony, this takes a few minutes max, so let's sleep 30s and check again"
-      sleep 30
+    while curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" |
+        jq '.[].title' | grep Contribution | grep $CEREMONY_BRANCH; do
+        echo "Oops, there's a PR from someone *right now* uploading a contribution to this ceremony, this takes a few minutes max, so let's sleep 30s and check again"
+        sleep 30
     done
 
     echo
@@ -108,22 +66,24 @@ prompt_env_inputs() {
     echo "Cloning ceremony branch $CEREMONY_BRANCH (this might take a while)..."
     echo
     git config --global lfs.fetchinclude none
-
     gh repo fork --clone $GITHUB_REPO -- ./ceremony --branch $CEREMONY_BRANCH --depth 2
     cd ./ceremony
+    CONTRIBUTOR_NAME="$(gh api user --jq '.login')"
+    git config user.name $CONTRIBUTOR_NAME
+    git config user.email $CONTRIBUTOR_NAME@users.noreply.github.com
+    repo_name=$(basename "$GITHUB_REPO")
+    default_repo=$CONTRIBUTOR_NAME/$repo_name
+    gh repo set-default $default_repo
     git reset --hard upstream/$CEREMONY_BRANCH # ensure everything is clean (important when fork already existed)
 
     . ceremony.env
     # set up user identity
-    CONTRIBUTOR_NAME="$(gh api user --jq '.login')"
-    git config user.name $CONTRIBUTOR_NAME
-    git config user.email $CONTRIBUTOR_NAME@users.noreply.github.com
 
     . /bin/tools.sh
 }
 
 check_contribute_env() {
-    CURRENT_CONTRIBUTION_FILE="$CONTRIBUTIONS_PATH/${CIRCUIT_FILENAME}_${CONTRIBUTOR_NAME}.zkey"
+    CURRENT_CONTRIBUTION_FILE="$CONTRIBUTIONS_PATH/${1}_${CONTRIBUTOR_NAME}.zkey"
     if [ -e "$CURRENT_CONTRIBUTION_FILE" ]; then
         echo "You've already contributed to this zk-voceremony in file $CURRENT_CONTRIBUTION_FILE"
         echo "Contributing more than once is not allowed. Aborting..."
@@ -131,50 +91,23 @@ check_contribute_env() {
     fi
 
     echo
-    while curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" \
-    | jq '.[].title' | grep Contribution | grep $CEREMONY_BRANCH ; do
-      echo "Oops, someone else started their contribution to this ceremony almost exactly at the same time as you."
-      echo "They will finish in a few minutes max, so let's sleep 30s and check again."
-      sleep 30
+    while curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/$GITHUB_REPO/pulls" |
+        jq '.[].title' | grep Contribution | grep $CEREMONY_BRANCH; do
+        echo "Oops, someone else started their contribution to this ceremony almost exactly at the same time as you."
+        echo "They will finish in a few minutes max, so let's sleep 30s and check again."
+        sleep 30
     done
 
     touch .lock && git add .lock && git commit .lock -m "Prevent other contributions" && git push origin $CEREMONY_BRANCH
-
     gh pr create --title "Contribution: from $CONTRIBUTOR_NAME to '$CEREMONY_BRANCH' ceremony" --body "" \
         --base $CEREMONY_BRANCH --draft
 
     git remote update -p
     git reset --hard upstream/$CEREMONY_BRANCH # discard .lock commit
-
-    # get the last contribution zkey file from the contributions file
-    if [ ! -f "$CONTRIBUTIONS_FILE" ]; then
-        error "contribution file does not exists, is the ceremony initialized?"
-        exit 1
-    else
-        LAST_CONTRIBUTION_FILE=$(get_last_contribution_file_path)
-        LAST_CONTRIBUTION_HASH=$(get_last_contribution_hash)
-    fi
-
-    echo
-    echo "Downloading artifacts..."
-    git config lfs.fetchinclude "${LAST_CONTRIBUTION_FILE##./}"
-    git lfs pull
-
-    echo
-    echo "
-You are going to contribute to '$CEREMONY_BRANCH' zk-voceremony process!"
-    echo
-    echo "Thanks $CONTRIBUTOR_NAME for your contribution!"
-    echo " - You are using $LAST_CONTRIBUTION_FILE as last contribution file ($HASH: $LAST_CONTRIBUTION_HASH)"
-    echo " - Your contribution will be saved in $CURRENT_CONTRIBUTION_FILE file"
-    echo
-    echo "Now, the script will prompt to you for an random input to generate the new contribution."
-    echo "This process will take a while... So, be patient and don't close the terminal until the process is finished.
-    "
 }
 
 make_contribution() {
-    CONTRIBUTION_RANDOM_INPUT=`ask_to_user "Please enter a random input and press enter:"`
+    CONTRIBUTION_RANDOM_INPUT=$(ask_to_user "Please enter a random input and press enter:")
     echo "Your part of the input is: '$CONTRIBUTION_RANDOM_INPUT'. Generating a random part..."
     CONTRIBUTION_RANDOM_INPUT="${CONTRIBUTION_RANDOM_INPUT}\n$(head -c 64 /dev/urandom | md5sum)"
     echo
@@ -182,69 +115,96 @@ make_contribution() {
     echo
     $SNARKJS zkc $LAST_CONTRIBUTION_FILE $CURRENT_CONTRIBUTION_FILE -e="$CONTRIBUTION_RANDOM_INPUT"
     [ $? -ne 0 ] && {
-        echo; echo "Error generating contribution, please retry or ask for support"
+        echo
+        echo "Error generating contribution, please retry or ask for support"
         exit 1
     } || {
-        echo; echo "Done! Your contribution generated in $CURRENT_CONTRIBUTION_FILE!"
+        echo
+        echo "Done! Your contribution generated in $CURRENT_CONTRIBUTION_FILE"
     }
     echo
 }
 
 append_hash_to_contributions() {
-    echo 
+    echo
     echo "Computing your contribution hash..."
     echo
 
-	local contribution_hash=$(get_file_hash "$1")
-	local contribution_filepath=$(basename -- "$1")
-	local contribution_line="$contribution_filepath:$contribution_hash"
-	# calculate the target line to append the contribution hash
-	total_lines=$(wc -l < "$CONTRIBUTIONS_FILE")
-	contribution_target_line=$((total_lines - 6))
-	last_contribution_target_line=$((total_lines))
-	# create a temporary file
+    local contribution_hash=$(get_file_hash "$1")
+    local contribution_filepath=$(basename -- "$1")
+    local contribution_line="$contribution_filepath:$contribution_hash"
+    # calculate the target line to append the contribution hash
+    total_lines=$(wc -l <"$CONTRIBUTION_FILE")
+    contribution_target_line=$((total_lines - 6))
+    last_contribution_target_line=$((total_lines))
+    # create a temporary file
     temp_file=$(mktemp)
     # copy lines up to the target line to the temporary file
-    head -n "$contribution_target_line" "$CONTRIBUTIONS_FILE" > "$temp_file"
+    head -n "$contribution_target_line" "$CONTRIBUTION_FILE" >"$temp_file"
     # append the new content
-    echo "$contribution_line" >> "$temp_file"
+    echo "$contribution_line" >>"$temp_file"
     # append the remaining lines after the new content
-    tail -n +$((contribution_target_line + 1)) "$CONTRIBUTIONS_FILE" >> "$temp_file"
-    # replace the original file with the temporary file including the new 
-	# last contribution hash
-	sed "${last_contribution_target_line}s/.*/$contribution_line/" $temp_file > "$CONTRIBUTIONS_FILE"
-}
+    tail -n +$((contribution_target_line + 1)) "$CONTRIBUTION_FILE" >>"$temp_file"
+    # replace the original file with the temporary file including the new
+    # last contribution hash
+    sed "${last_contribution_target_line}s/.*/$contribution_line/" $temp_file >"$CONTRIBUTION_FILE"
 
-publish_contribution() {
-    echo 
-    echo "Uploading and committing your contribution..."
-    echo
-    git add $CONTRIBUTIONS_FILE $CURRENT_CONTRIBUTION_FILE && \
-        git commit -m "Contribution: from $CONTRIBUTOR_NAME to '$CEREMONY_BRANCH' ceremony" \
-        && git push -f origin $CEREMONY_BRANCH \
-        && gh pr ready
-    [ $? -ne 0 ] && {
-        echo; echo "Error during the contribution process, please start it over or ask for support"
-        exit 1
-    } || {
-        echo; echo "Done! Your contribution has been published!"
-    }
-    echo
-    echo "Last but not least, help us to get more contributors by sharing the following tweet:
-
-'I participated in the @vocdoni zk ceremony at https://zk.vocdoni.io/ to contribute towards securing anonymous voting.'"
-    echo
-    echo "Thanks for your contribution! :)"
-    echo
+    cat "$CONTRIBUTION_FILE"
 }
 
 init_contribution() {
     intro_message
     prompt_env_inputs
-    check_contribute_env
-    make_contribution || error "contribution failed"
-    append_hash_to_contributions "$CURRENT_CONTRIBUTION_FILE"
-    publish_contribution || error "publish contribution failed"
+    original_contribution_path="$CONTRIBUTIONS_PATH"
+    contribution_file_names=($(ls -1p $CONTRIBUTIONS_PATH | grep / | sed 's:/*$::'))
+    for circuit_folder in "${contribution_file_names[@]}"; do
+        CONTRIBUTION_FILE="$original_contribution_path/$circuit_folder/CONTRIBUTIONS.md"
+        CONTRIBUTIONS_PATH="$original_contribution_path/$circuit_folder"
+        echo "Checking if you are already contributing to '$circuit_folder' zk-ceremony..."
+        echo "Checking if $CONTRIBUTION_FILE exists..."
+        # get the last contribution zkey file from the contributions file
+        if [ ! -f "$CONTRIBUTION_FILE" ]; then
+            error "contribution file does not exists, is the ceremony initialized?"
+            exit 1
+        fi
+
+        LAST_CONTRIBUTION_HASH=$(get_last_contribution_hash "$CONTRIBUTION_FILE")
+        echo "Last contribution hash: $LAST_CONTRIBUTION_HASH"
+        LAST_CONTRIBUTION_FILE=$(get_last_contribution_file_path "$circuit_folder" "$CONTRIBUTIONS_PATH")
+        echo "Last contribution file: $LAST_CONTRIBUTION_FILE"
+
+        echo "You are going to contribute to '$CEREMONY_BRANCH' zk-ceremony process!"
+        echo " - You are using $LAST_CONTRIBUTION_FILE as last contribution file ($HASH: $LAST_CONTRIBUTION_HASH)"
+
+        echo "Downloading artifacts..."
+        git config lfs.fetchinclude "${LAST_CONTRIBUTION_FILE##./}"
+        git lfs pull
+
+        check_contribute_env $circuit_folder || error "contribute env failed"
+        echo " - Your contribution will be saved in $CURRENT_CONTRIBUTION_FILE file"
+        echo
+        echo "Now, the script will prompt to you for an random input to generate the new contribution."
+        echo "This process will take a while... So, be patient and don't close the terminal until the process is finished."
+        make_contribution || error "contribution failed"
+        append_hash_to_contributions "$CURRENT_CONTRIBUTION_FILE" $circuit_folder
+    done
+
+    echo "Uploading and committing your contribution..."
+    echo "$original_contribution_path"
+    git add $original_contribution_path &&
+        git commit -m "Contribution: from $CONTRIBUTOR_NAME to '$CEREMONY_BRANCH' ceremony"
+    git push -f origin $CEREMONY_BRANCH && gh pr ready
+    [ $? -ne 0 ] && {
+        echo
+        echo "Error during the contribution process, please start it over or ask for support"
+        exit 1
+    } || {
+        echo
+        echo "Done! Your contribution has been published!"
+    }
+    echo "Thanks for your contribution! :)"
+    echo
+
 }
 
 init_contribution
